name: "CI"

run-name: ${{ github.actor }} invoked Terraform Apply 

on:
  push:
    branches: [main, feature/**]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
      - "Diagram/**"
      - ".github/workflows/**"

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
  TF_WORKSPACE: "${{ secrets.TF_WORKSPACE }}"
  ROOT_CONFIG_DIRECTORY: "./"

jobs:
  deploy:
    name: "CI"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Terraform Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: apply-upload
        with:
          directory: ${{ env.ROOT_CONFIG_DIRECTORY }}
          workspace: ${{ env.TF_WORKSPACE }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Terraform Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"